# Generated by Django 5.2.14 on 2026-05-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=150)),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField()),
                ('nombre_voyageurs', models.PositiveIntegerField()),
                ('type_voyage', models.CharField(choices=[('famille', 'Voyage en famille'), ('couple', 'Voyage en couple'), ('business', 'Voyage business'), ('groupe', 'Voyage en groupe'), ('lune_miel', 'Lune de miel')], max_length=30)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('message', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
    ]
