"""
Django settings for breavy project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url
from decouple import config

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = ['*']  # tu affineras plus tard


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ← ajouter ici
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'breavy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'breavy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL')
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "pages/static"),  # ✅ Django ira chercher les fichiers statiques ici
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DUFFEL_API_KEY = os.environ.get("DUFFEL_API_KEY", "duffel_test_v2wGYggjTmo_5rJjEInuDFmRqScU3Q4mca7XrUnyxaT")
DUFFEL_API_URL = "https://api.duffel.com"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─── À AJOUTER dans votre settings.py ───────────────────────────────────────

# ── Stripe ──
STRIPE_SECRET_KEY     = os.environ.get("STRIPE_SECRET_KEY",  "pk_live_51TTLT8GedyXqjcYdGL5IatOrocjUQ5QdFS2pBrpFwaCtCup1jPwR4yT3bhnWpoHkPm1h37FLAKgqU9spywSCFW1n00celIbMcv")
STRIPE_PUBLIC_KEY     = os.environ.get("STRIPE_PUBLIC_KEY",  "pk_live_51TTLT8GedyXqjcYdGL5IatOrocjUQ5QdFS2pBrpFwaCtCup1jPwR4yT3bhnWpoHkPm1h37FLAKgqU9spywSCFW1n00celIbMcv")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "pk_live_51TTLT8GedyXqjcYdGL5IatOrocjUQ5QdFS2pBrpFwaCtCup1jPwR4yT3bhnWpoHkPm1h37FLAKgqU9spywSCFW1n00celIbMcv")
# Obtenez vos clés sur https://dashboard.stripe.com/apikeys

# ── Email SMTP (exemple Gmail) ──
EMAIL_BACKEND       = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST          = "smtp.gmail.com"
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = "votre@gmail.com"
EMAIL_HOST_PASSWORD = "votre_mot_de_passe_application"
# Pour Gmail : activez "Mot de passe d'application" dans les paramètres de sécurité Google.
# Pour Mailgun / SendGrid : changez HOST/PORT selon leur documentation.

DEFAULT_FROM_EMAIL  = "Breavy Voyages <reservation@breavyvoyages.com>"
OPS_EMAIL           = os.environ.get("OPS_EMAIL", "ops@breavyvoyages.com")

# ── Duffel (déjà dans views.py, mais mieux ici pour la production) ──
# DUFFEL_API_KEY est défini plus haut — passer la vraie clé via .env : DUFFEL_API_KEY=duffel_live_XXXXX

# HotelBeds API
HOTELBEDS_API    = os.environ.get("HotelBeds_API", "")
HOTELBEDS_SECRET = os.environ.get("HotelBeds_SECRET", "")
HOTELBEDS_ENV     = os.environ.get("HOTELBEDS_ENV", "test")  # "test" ou "production"
 
# Cache (Django cache framework) — Redis recommandé en production
# pip install django-redis
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        # En production avec Redis :
        # "BACKEND": "django_redis.cache.RedisCache",
        # "LOCATION": "redis://127.0.0.1:6379/1",
    }
}
 
# Logging HotelBeds
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "": {  # root logger
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}
 
CSRF_TRUSTED_ORIGINS = [
    "https://supplier-overture-semifinal.ngrok-free.dev",
]
# ─────────────────────────────────────────────────────────────
#  FICHIER .env (à la racine du projet, JAMAIS commité sur Git)
# ─────────────────────────────────────────────────────────────
# HOTELBEDS_API_KEY=votre_vraie_api_key
# HOTELBEDS_SECRET=votre_vrai_secret
# HOTELBEDS_ENV=test
 
 
# ─────────────────────────────────────────────────────────────
#  DÉPENDANCES — pip install
# ─────────────────────────────────────────────────────────────
# pip install requests django python-dotenv
# Optionnel: pip install django-redis



